version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    links:
      - redis:redis
    volumes:
      - ./marketinfo:/marketinfo
    command: sh -c "gunicorn marketinfo.wsgi:application -w 2 -b :8000 "
    environment:
      - DEBUG=1
  
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata: